### PR TITLE
Removed psycopg/pymongo dependency

### LINKED ISSUE #19: Install shouldn't fail if I don't have pg_config
If I'm working with MySQL or SQLITE, I shouldn't need to install postgresql to use this library. Could this be optional somehow instead?

### PR DESCRIPTION
**Pull request by mauricioabreu**
Fixes #19

### CODE REVIEW

**Comment by mauricioabreu** [comment]
I think the docs should not be responsible to tell the user how to install postgresql.
I left that part in the docs because it should be a different commit IMO.

**Comment by emirozer** [comment]
Will you be contributing to this PR ? Because with these changes postgresql and mongodb won't work at all :)

**Comment by mauricioabreu** [comment]
Yes I will. They wont stop working. Actually it is better now since it does
not add optional dependencies forcing users to install useless dependencies
for them. Before my commit mysql was optional. Now everything is optional.
What do you think?
Em 12/01/2015 14:04, "Emir Ozer" <notifications@github.com> escreveu:

**Comment by emirozer** [comment]
Well the difference between mysql and the others is that mysql adapter is external, so the user has to get it themselves. (of course this can be automated but i kind of chose not to)
Removing requirements is ok as long as the program can be reactive to it. 
For example if i merge this pr and try to generate mongodb or postgresql i will just face an error that the imported package in mongodb handler and the imported package in postgresql handler is not installed on to python packages.

**Comment by mauricioabreu** [comment]
This is why I think everything should be optional. Docs would serve to
recommend users to install such dependencies. I think missing dependencies
is better than "forcing" users to install non used dependencies. what are
your thoughts?
Em 13/01/2015 08:20, "Emir Ozer" <notifications@github.com> escreveu:

**Comment by emirozer** [comment]
Ok i agree with your point, but for the people who are lazy i was thinking at the time of import i can fix it for them ? Like, after merging your pr i can do something in the lines of this :


    package_marker = subprocess.check_output("pip list", shell=True)
    package_marker = package_marker.split('\n')
    package_flag = False

    for p in package_marker:
        if p.startswith('pymongo'):
            package_flag = True

    if not package_flag:
        print "pymongo package is not found on the local python packages"
        print "would you like me to install it for you [y/N] ? "
        user_warn = raw_input()
        if user_warn == "y":
            subprocess.call("pip install pymongo", shell=True)
        else:
            sys.exit(0)

**Comment by emirozer** [comment]
Would this be okay with you ? what is your opinion ?

**Comment by mauricioabreu** [comment]
Being honest with you, I think you should just let the expection raise. you
can of course wrap the exception and give your own message but I like to
keep things simple. You can reject or close my PR now and think about it
later. Thanks anyway.

**Comment by emirozer** [comment]
Thank you for the honesty, i don't want to come to a conclusion, let me think on this a bit ! ^_^

**Comment by emirozer** [comment]
Ok, an experienced friend of mine also pointed that this is the natural way of handling this situation.
I am merging your PR and i will ONLY add meaningful exception raises.

**Comment by mauricioabreu** [comment]
Thanks.
Em 13/01/2015 13:18, "Emir Ozer" <notifications@github.com> escreveu:

**Pull request merged**
