### PR TITLE
Change import paths to fix #31

### LINKED ISSUE #31: Error when running cli
I tried with and without a virtualenv for dependency isolation, using the following command:

`fake2db --db postgresql --host 0.0.0.0 --port 5632 --password password --username user --rows 10 --name mydb`

Which gave me:

```python
File "/usr/local/bin/fake2db", line 7, in <module>
    from fake2db.fake2db import main
  File "/usr/local/lib/python3.5/site-packages/fake2db/fake2db.py", line 6, in <module>
    from custom import faker_options_container
ImportError: No module named 'custom'
```

But the `custom.py` file exists, it's just not finding it. Installed using pip 9.0.1 and python 2.7.10.

`sudo`  seems to work to bypass the error. Not sure why it needs it, but this is probably unrelated to the specific package, so I'll close this.

### PR DESCRIPTION
**Pull request by vzhong**
The code works again after I changed the import paths as shown here. This fixes #31 for me.

### CODE REVIEW

**Comment by emirozer** [comment]
I had problem reproducing this issue and was about to ask for the reporters for their env information.
Thank you very much for the contribution, let me test in my vm's and my local see how its turned out to be.

I will update very soon!

**Comment by emirozer** [comment]
So I am on Python 2.7.12 and Ubuntu 16.04.2 LTS, I cloned your fork to test it out, locally if I do:

```
fake2db|master ⇒ python fake2db.py --db postgresql --host localhost --port 5432 --password abc --username abc --rows 10
Traceback (most recent call last):
  File "fake2db.py", line 6, in <module>
    from fake2db.custom import faker_options_container
  File "/home/eoz/Personal/vzhong/fake2db/fake2db/fake2db.py", line 6, in <module>
    from fake2db.custom import faker_options_container
ImportError: No module named custom
```

Then I setup.py install your fork:

```
fake2db|master ⇒ fake2db --db postgresql --host localhost --port 5432 --password abc --username abc --rows 10 
Traceback (most recent call last):
  File "/usr/local/bin/fake2db", line 11, in <module>
    load_entry_point('fake2db==0.5.1', 'console_scripts', 'fake2db')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2589, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2249, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2255, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/fake2db/fake2db.py", line 6, in <module>
ImportError: No module named custom
```


What is your environment details can you share ?

**Comment by emirozer** [comment]
Also do you use PYTHONPATH ?

**Comment by vzhong** [comment]
Hmm interesting.. I don't use `PYTHONPATH`. This works for me on Python3
but not Python2.

**Comment by vzhong** [comment]
Hmm interesting.. I am on OSX and I don't use `PYTHONPATH`. This works for me on Python3
but not Python2. It's very strange because I can do the line that is failing manually in `python2`:

```python
vzhong@vzhong-ltm2: ~/tmp
 $ /usr/local/opt/python/bin/python2.7                                        [20:49:10]
Python 2.7.13 (default, Dec 17 2016, 23:03:43)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from fake2db.custom import faker_options_container
```

**Comment by vzhong** [comment]
Ahhhh I think the problem is this: [relative imports are no longer supported in Python3](http://stackoverflow.com/questions/12172791/changes-in-import-statement-python3). Hence, the `from custom import *` calls no longer work in Python3.

**Comment by emirozer** [comment]
I will push a fix soon, thanks for your contribution though!

**Pull request closed without merging**
