### PR TITLE
[WIP] Docker support

### PR DESCRIPTION
**Pull request by brunowego**
The makefile helps with the build and publish. 😄

### CODE REVIEW

**Comment by brunowego** [comment]
# Docker

## MySQL

```sh
docker run --detach \
  --network host \
  --env MYSQL_ROOT_PASSWORD=root \
  --publish 3306:3306 \
  --name mysql \
  mysql:8.0
```

```sh
docker run -it --network host emirozer/fake2db --rows 250 --db mysql --username root --password root
```

**Comment by emirozer** [comment]
Sweet! rock on dude thanks for the contribution. Just ping me here whenever you want this to be merged!

**Comment by brunowego** [comment]
I am working to test every database that you are supporting.

**Comment by brunowego** [comment]
## MongoDB

```sh
docker run --detach \
  --env MONGO_INITDB_ROOT_USERNAME=root \
  --env MONGO_INITDB_ROOT_PASSWORD=root \
  --network host \
  --name mongo \
  mongo:4.1
```

```sh
docker run -it --network host emirozer/fake2db --rows 250 --db mongodb --name admin --username root --password root
```

**Comment by brunowego** [comment]
A future step, and a improvement, is separate each db in a separated docker image.

**Comment by brunowego** [comment]
## Redis

```sh
docker run -it -v $(pwd):/usr/data/dump emirozer/fake2db --rows 250 --db redis
```

**Comment by brunowego** [comment]
About CouchDB, I never work with this before, but is it a good opportunity to that. Alpine not have a CouchDB package, need build this. I will do that soon as possible ;)

**Pull request closed without merging**
